#!/usr/bin/env python
import sys
import datetime as d

def main():
    args = sys.argv

    command = args[1]
    data = args[2]

    date = str(d.date.today())
    
    
    
if __name__ == "__main__":
    main()