#!/usr/bin/env python
import sys
import datetime as d

sys.path.append("./functions")

import add
import makeFile

def main():
    args = sys.argv

    command = args[1]
    data = args[2]

    date = str(d.date.today())

    file = makeFile.createFile(date)
    file.write(data)


if __name__ == "__main__":
    main()